services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-pdv
    ports:
      - "3033:3033"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: ["bun", "start"]
